### ISSUE TITLE
Add Report Button

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#100]
The idea about this is to implement a report button for repositories that are spam but also have the "hacktoberfest" label.

Once a repo is reported, it should be manually reviewed by either me or someone else and then it can be added to a list of filtered repositories

**Comment by Mohit030802** [comment]
I can Solve this

**Comment by inbuilt-aura** [comment]
Hey, i am very familiar with typescript and i would love to contribute, if you give me a chance.I would love to contribute.

**Comment by max-programming** [comment]
Sure @inbuilt-aura but I guess @Mohit030802 already opened a PR. Maybe you can enhance upon that once it is merged

**Comment by inbuilt-aura** [comment]
@max-programming ok sure,will wait until merged

**Comment by Mohit030802** [comment]
Hi, @max-programming can review #146 ? and tell me any updates on this.

**Comment by inbuilt-aura** [comment]
@max-programming, hey I think they have completed,now can I contribute?

**Comment by max-programming** [comment]
I'll be working on the backend functionality of this issue
