### ISSUE TITLE
The readability in this website is no so good because of the similar text color and the background color.

### ISSUE THREAD

**Issue by kantakshay** [max-programming/hacktoberfest-projects#106]
![Screenshot (163)](https://github.com/max-programming/hacktoberfest-projects/assets/84266746/f3d1c7ce-84f6-496d-9cb8-173afdfd1c2b)
![Screenshot (164)](https://github.com/max-programming/hacktoberfest-projects/assets/84266746/b9a112ed-bdc5-4015-9b9d-a97d996b261d)

**Comment by inbuilt-aura** [comment]
Hey,i would love to contribute on this issue.Plzz assign me, i think i can fix it for you.

**Comment by kantakshay** [comment]
@inbuilt-aura it is fixed

**Comment by inbuilt-aura** [comment]
@kantakshay,then plzz close the issue and are there any other issues?

**Comment by malik-vishu** [comment]
@kantakshay @inbuilt-aura issue 98 already assigned

**Comment by inbuilt-aura** [comment]
@kantakshay any issue is open which i could contribute?

**Comment by kantakshay** [comment]
@inbuilt-aura  @malik-vishu I have fixed the issue and raised a PR #107

**Comment by kantakshay** [comment]
@inbuilt-aura find the issue dude!

**Comment by malik-vishu** [comment]
@kantakshay could you please remove your PR since it was already assigned.
