### ISSUE TITLE
Text and Icons color issue

### ISSUE THREAD

**Issue by sarmadhamdani02** [max-programming/hacktoberfest-projects#109]
Hey there! 👋 I've noticed some issues with the text and icon/button colors in these images. The colors are currently black which is making them a bit hard to read. To improve the overall readability, we should change these to a lighter color, like white or a contrasting shade. 

![image](https://github.com/max-programming/hacktoberfest-projects/assets/111639663/ce8f3348-9589-4cd3-ad74-cde09c015b5b)
![image](https://github.com/max-programming/hacktoberfest-projects/assets/111639663/3046eac4-3def-40e1-93fc-7ef91cd9d472)
![image](https://github.com/max-programming/hacktoberfest-projects/assets/111639663/f7c4ade0-01d7-42e4-a877-9744774dbaa0)

**Comment by sarmadhamdani02** [comment]
@max-programming 
Kindly assign this issue to me, I would love to work on this. 😄

**Comment by malik-vishu** [comment]
@sarmadhamdani02 issue 98 assigned

**Comment by max-programming** [comment]
@sarmadhamdani02 Actually Malik already took this up

**Comment by sarmadhamdani02** [comment]
@max-programming 
No problem.
