### ISSUE TITLE
Need Some Padding from Left and Right on Main List Section 

### ISSUE THREAD

**Issue by LynxSumit** [max-programming/hacktoberfest-projects#110]
**Issue Description**:
I would like to request the addition of left and right padding to the repository card displayed on the GitHub repository page. Currently, the repository card appears to be lacking padding, and this affects the overall visual aesthetics and readability of the content.

- Please consider the impact of this change on responsive design, ensuring that it works well on various screen sizes.
- It's important that the padding is consistent and does not interfere with other elements on the page.

![Screenshot 2023-09-30 154539](https://github.com/max-programming/hacktoberfest-projects/assets/114245865/de4006d1-6699-4275-894d-55b9735f2678)

I would like to work on this issue. Thank you in advance.

**Comment by max-programming** [comment]
Thanks for noticing this! Assigned it to you ✌️

**Comment by Keshavraj52** [comment]
I hope this message finds you well! I'm eager to contribute more to our project. plz assign this issue to me i will fix it

**Comment by p7uverma** [comment]
May I take this task
