### ISSUE TITLE
style: add border/bg of search button

### ISSUE THREAD

**Issue by priyankarpal** [max-programming/hacktoberfest-projects#112]
currently, if we hover over the button it will show a bg but we should add a border/bg. I want to work on this issue. 
![image](https://github.com/max-programming/hacktoberfest-projects/assets/88102392/7982a73b-3282-4bf5-8ec1-4409d30e74d8)

**Comment by max-programming** [comment]
You can surely take this up ✌️

**Comment by max-programming** [comment]
You can surely take this up ✌️

**Comment by Keshavraj52** [comment]
I hope this message finds you well! I'm eager to contribute more to our project. plz assign this issue to me
