### ISSUE TITLE
chore(dep): migrate to `pnpm` 

### ISSUE THREAD

**Issue by priyankarpal** [max-programming/hacktoberfest-projects#115]
Currently, we are using `npm` for this project, but `npm` has a few problems. 

`pnpm`:

- Saves disk space by not duplicating packages.
- Faster installations due to shared packages.
- Reduces bandwidth usage by downloading packages once.
- Uses efficient linking for quicker operations.
- Ensures better project isolation.

`npm`:

- May consume more disk space due to duplicated packages.
- Slower installations compared to pnpm.
- May use more bandwidth by downloading packages for each project.
- Performs standard package installations.

pnpm docs: https://pnpm.io/benchmarks

### Note: I want to work on this issue

**Comment by max-programming** [comment]
Sure I am okay with using pnpm. But for people who want to use npm, will the pnpm lockfile support that?

**Comment by priyankarpal** [comment]
They need to install PNPM on their machine before proceeding.

**Comment by max-programming** [comment]
What's the worst that can happen if they use npm. Because I don't want to force pnpm to everyone

**Comment by priyankarpal** [comment]
it's not a bad choice, and `npm` is widely used in the Node.js ecosystem. However, like any tool, it has its strengths and weaknesses that's why.

**Comment by max-programming** [comment]
Alright, then you can configure pnpm.
I also use pnpm on a lot of occasions and it is golden!
