### ISSUE TITLE
Fix Text overflow in Small Screens

### ISSUE THREAD

**Issue by p7uverma** [max-programming/hacktoberfest-projects#118]
Hi I'm @p7uverma,
When we shrink website page repo name gets overflow.

![text-overflow](https://github.com/max-programming/hacktoberfest-projects/assets/112266318/c0f83e21-8827-42b3-bcfb-bc07a091515a)

## I fixed this and the pull request is => #117

**Comment by sadiksaifi** [comment]
fixed in pr #127
