### ISSUE TITLE
[BUG] Error 404 on Best Match

### ISSUE THREAD

**Issue by ScalarJerk** [max-programming/hacktoberfest-projects#120]
From home page I chose C language. Then I filtered according to Most Help Wanted Issues. 
The page doesn't come up but sometimes it does.

**Comment by max-programming** [comment]
@ScalarJerk Sometimes this happens due to slow internet. When you see a proper url, a refresh might fix that
![image](https://github.com/max-programming/hacktoberfest-projects/assets/51731966/05428416-94a5-4d49-bb01-bf9e0777d80a)

**Comment by ScalarJerk** [comment]
But it sure is a bug imo 🧐@max-programming

**Comment by max-programming** [comment]
I understand now.
@ScalarJerk that happens due to the amount of requests to GitHub API and it rate limits to a certain number of requests.

Will find a solution to that

**Comment by max-programming** [comment]
Should be fixed after 7aa1c84
