### ISSUE TITLE
bug: /repos/javascript results in 404

### ISSUE THREAD

**Issue by ArslanYM** [max-programming/hacktoberfest-projects#122]
![results in 404](https://github.com/max-programming/hacktoberfest-projects/assets/104521101/79c1da72-d553-4658-9209-57ee3e7e840e)

**Comment by max-programming** [comment]
@ArslanYM Try refreshing the page. It should work

**Comment by sadiksaifi** [comment]
@ArslanYM you can try using https://www.hacktoberfest.live/ it won't crash, I've deployed it on vercel which can handle sufficient amount of traffic on my plan and also I've bought this domain hacktoberfest.live for website @max-programming.

**Comment by max-programming** [comment]
@sadiksaifi Is this a fork?

**Comment by max-programming** [comment]
Should be fixed after 7aa1c84

**Comment by sadiksaifi** [comment]
> @sadiksaifi Is it a fork?

Yes

**Comment by sadiksaifi** [comment]
> Should be fixed after 7aa1c84

Ok, cool
