### ISSUE TITLE
[BUG] Stars filter not getting reset on updating the language

### ISSUE THREAD

**Issue by NishidhJain** [max-programming/hacktoberfest-projects#129]
When the user changes the language after apply stars filter, the new url does not contains the stars filter but the value in the stars input still remains the same as old.

Selecting any language & applying stars filter

![image](https://github.com/max-programming/hacktoberfest-projects/assets/61869195/d2a0dd1c-ad80-463d-b235-ffe3bc25ec2a)

Now updating the language again 

![image](https://github.com/max-programming/hacktoberfest-projects/assets/61869195/17981914-4d25-47c7-9cd8-2f62f461d660)

The query params for stars filter is removed but the values in the filter is still their, this should get cleared instead.

Steps to reproduce:

1. Go to https://hacktoberfest-projects.vercel.app/
2. Select or search any language
3. Apply stars rating filter
4. Now update the language to something else, and not the query params and stars filter values

@max-programming I would be happy to work on this issue.

If it looks good to you then please assign this to me

Thank You,
Nishidh Jain

**Comment by max-programming** [comment]
Alright then. You can take up this issue

**Comment by NishidhJain** [comment]
PR #136 fixes this bug
