### ISSUE TITLE
Unequal spacing between this buttons

### ISSUE THREAD

**Issue by snehafarkya** [max-programming/hacktoberfest-projects#130]
Hi, @max-programming! I'm Sneha from India, a Frontend developer, and a Technical writer. I saw your website and it looks dope however there are some UI-related changes. 
This unequal space doesn't look good. I'll give it an equal spacing 
Assign this task to me under **hacktoberfest** label ✨

![image](https://github.com/max-programming/hacktoberfest-projects/assets/63949465/fb779845-b18f-4209-aac6-f71c70e51fc3)

Thank you and have a nice day!

**Comment by max-programming** [comment]
Sure thing! Go ahead!

**Comment by snehafarkya** [comment]
Hey @max-programming , it's done ✨. Looking forward to a successful merge. 
Thank you!

**Comment by snehafarkya** [comment]
Hey @max-programming , can you add **Hacktoberfest-accepted** label to this because: 
![image](https://github.com/max-programming/hacktoberfest-projects/assets/63949465/e95f89b8-bc81-47b9-ac57-cd58c4fbe6a3)

**Comment by max-programming** [comment]
The issue doesn't need to have the label. And the PR is merged, it'll take sometime to update on their site.

Check it after an hour or two and it will show accepted. Let me know if it doesn't
