### ISSUE TITLE
Making the search button autocomplete disable

### ISSUE THREAD

**Issue by maitri-vv** [max-programming/hacktoberfest-projects#132]
There's history of searched items visible over clicking on the search button, it should be kept "autocomplete off" to prevent it from invading privacy of user. Also it takes cookies data, which displays vague items searched by user in context to some other search bar.
Screenshot:
![image](https://github.com/max-programming/hacktoberfest-projects/assets/87691594/8c0fd543-b1aa-46bb-a034-159e2746d202)

Please assign under hacktoberfest 2023 :)

**Comment by max-programming** [comment]
Sure you can take this up. Thank you. 
Also as an extra little fix can you change the color of the magnifying glass to a brighter color defined in the tailwind config?

**Comment by maitri-vv** [comment]
sure will do it

**Comment by maitri-vv** [comment]
hey @max-programming please label it for hacktoberfest :)

**Comment by max-programming** [comment]
When the pull request will be merged it will show up as accepted in hacktoberfest so don't worry
