### ISSUE TITLE
Search Button should be at top

### ISSUE THREAD

**Issue by Jaspreet099** [max-programming/hacktoberfest-projects#135]
<img width="652" alt="Screenshot 2023-10-02 at 3 07 58 PM" src="https://github.com/max-programming/hacktoberfest-projects/assets/75212002/851438e2-d7b3-4e2d-886a-9663e08f5ece">

Placing the search button at the top of the interface will enhance the user experience significantly. Furthermore, increasing its width will ensure that the placeholder text is displayed correctly. This combination of design choices can contribute positively to the overall usability of the system.

**Comment by nidble** [comment]
Hi there, can I work on this?

**Comment by max-programming** [comment]
@Jaspreet099 @nidble This search is actually different than the search box on the navbar. Maybe I should rename it to something other than search.

**Comment by nidble** [comment]
@Jaspreet099 and @max-programming I started to write a solution where the form is moved on the top (but not in the nav bar). I'm going to push it...
Please let me know if it is working or not, and I will improve.
Let me ask also if this PR is also eligible for Hackotoberfest, and if so, if you please add the label  🙏

**Comment by max-programming** [comment]
All PRs are eligible for hacktoberfest so no worries about that.

Anyways, do show your solution in a PR @nidble I'd love to see what you come up with

**Comment by nidble** [comment]
hello @max-programming, PR submitted, wdyt?
