### ISSUE TITLE
404 when clicking SEARCH directly on homepage without input

### ISSUE THREAD

**Issue by prithvi2k2** [max-programming/hacktoberfest-projects#138]
On the homepage, when we click on search🔍 button directly, without providing any input text or providing just blank spaces takes the user to a 404 page.

**Expected**: Prompt user to provide input
**Actual**: Considers empty field as input and couldn't perform a proper search

If this issue is concerning, allow me to fix it.

![image](https://github.com/max-programming/hacktoberfest-projects/assets/72189314/6fc00442-40bd-4821-bffc-b1f1883fd9eb)

**Comment by max-programming** [comment]
Thanks for creating an issue. Should be an easy fix. Go ahead!

**Comment by prithvi2k2** [comment]
> Thanks for creating an issue. Should be an easy fix. Go ahead!

@max-programming Yes, it is an easy fix indee. Opened a PR - #142
