### ISSUE TITLE
[Responsiveness Issue] Header of the website is not responsive

### ISSUE THREAD

**Issue by NishidhJain** [max-programming/hacktoberfest-projects#140]
I will make the header of the website responsive, attaching the screenshots of before and after. If you like this, please **assign** this to **me**, would be happy to **contribute** for the same.

Before

<img width="1437" alt="Screenshot 2023-10-02 at 5 54 02 PM" src="https://github.com/max-programming/hacktoberfest-projects/assets/61869195/f81d1f4d-78f5-4bb4-b60d-9bc4aafd8002">

After

<img width="1438" alt="image" src="https://github.com/max-programming/hacktoberfest-projects/assets/61869195/b827b253-c846-41d4-8d09-937e76f8c497">

Mobile Device Screenshot

![iPhone 12 Pro-1696249678579](https://github.com/max-programming/hacktoberfest-projects/assets/61869195/37112a79-4104-4308-b222-e9a8576833ea)

Thank You,
Nishidh Jain

**Comment by max-programming** [comment]
Thanks for taking this task of making it responsive!
