### ISSUE TITLE
Search button color scheme

### ISSUE THREAD

**Issue by malik-vishu** [max-programming/hacktoberfest-projects#150]
# Please assign this to me
![finder_proj_missing_search](https://github.com/max-programming/hacktoberfest-projects/assets/127117253/441ed8c0-1f6d-4f3e-87dc-28f4f4bd085d)

Text should be visible.

**Comment by malik-vishu** [comment]
@max-programming Can you assign this to me?

**Comment by malik-vishu** [comment]
@max-programming should I use manga-2?

**Comment by malik-vishu** [comment]
I just saw this. Do you want me to change the color of GitHub icon to white?
![image](https://github.com/max-programming/hacktoberfest-projects/assets/127117253/67a0d4db-dad1-48a4-9519-37dd319d1c16)

**Comment by max-programming** [comment]
Yeah sure

**Comment by max-programming** [comment]
> @max-programming should I use manga-2?

yes

**Comment by malik-vishu** [comment]
@max-programming Nishidh changed a lot of things so it was conflicting.
Creating a new pull request please check.
