### ISSUE TITLE
Include footer in all the pages

### ISSUE THREAD

**Issue by irfan-iiitr** [max-programming/hacktoberfest-projects#152]

**Comment by nidble** [comment]
Hello @irfan-iiitr, can I work on this?

**Comment by Mohit030802** [comment]
Hi @max-programming can I work on this as well?

**Comment by max-programming** [comment]
@Mohit030802 Not sure if you both can work on it. It's a simple task after all

**Comment by Mohit030802** [comment]
Hi @max-programming can you review my PR #176

**Comment by max-programming** [comment]
Sorry @nidble I didn't realize Mohit opened the PR for this task which was assigned to you and I merged it.
