### ISSUE TITLE
[BUG] Star's range filter allow negative input

### ISSUE THREAD

**Issue by beyzanur-seyhan** [max-programming/hacktoberfest-projects#155]
Star filter input fields accept negative values. When I search, it redirects me to a 404 page. I think this is a bug. Inputs should not accept negative values. There should not be a situation where negative values ​​can be accepted. Please assign me to this issue. I think I can solve this issue.

![image](https://github.com/max-programming/hacktoberfest-projects/assets/80166639/357cc110-84f0-4ce5-b881-deb3e52278d1)

![image](https://github.com/max-programming/hacktoberfest-projects/assets/80166639/58c44342-505e-45d7-8a98-b497c48f7630)

**Comment by max-programming** [comment]
For sure! Thanks for working on it @beyzanur-seyhan
