### ISSUE TITLE
[BUG] Dropdown menu stays open

### ISSUE THREAD

**Issue by beyzanur-seyhan** [max-programming/hacktoberfest-projects#164]
After clicking on the language dropdown and selecting an option, the relevant results appear, but the dropdown options continue to appear. Dropdown menu disappears when you click anywhere. I think this is a bug.

Can you assign me to this issue?

![image](https://github.com/max-programming/hacktoberfest-projects/assets/80166639/dcdeda58-d567-41c0-a578-414b2aae7006)

**Comment by max-programming** [comment]
Alright then @beyzanur-seyhan

**Comment by beyzanur-seyhan** [comment]
> Alright then @beyzanur-seyhan 

Thanks
