### ISSUE TITLE
Card sub header text not visible

### ISSUE THREAD

**Issue by 9josky** [max-programming/hacktoberfest-projects#166]
As at the time i am writing this, the description of each repo in the card is not visible, i propose to make the color white to match with the border colors of each card.

@max-programming Kindly assign this to me.

![Screenshot (9)1](https://github.com/max-programming/hacktoberfest-projects/assets/24679488/cabb3d41-9df6-4044-b563-c1c49913e954)

**Comment by max-programming** [comment]
This has been fixed now. Thanks!
