### ISSUE TITLE
Contributor card layout appears to be inconsistent

### ISSUE THREAD

**Issue by nabarvn** [max-programming/hacktoberfest-projects#177]
Screenshot for reference:

![Contributor Card Layout Issue](https://github.com/max-programming/hacktoberfest-projects/assets/64539836/102e3a42-75ef-44fe-b38c-67da23487a5f)

I can work on it if you want, @max-programming.

**Comment by max-programming** [comment]
Sure! But I request no one to open a PR on an issue that is already assigned to someone

**Comment by Vivek-04022001** [comment]
@max-programming, I'm interested in contributing to this project. However, I've noticed that all the issues are currently assigned. If possible, could you assist me in finding an available issue to work on?

**Comment by max-programming** [comment]
I understand @Vivek-04022001 
I'd suggest if there are no issues you can take then it's better to analyze the project yourself and see what bugs you encounter, and what features are missing.

You will hopefully find something interesting to do
