### ISSUE TITLE
Uneven size and spacing of elements in responsive design

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#188]
Right now in responsive design, the size of these elements is uneven. It'll be better to make them the same-sized. With that, also comes the uneven margin

![WhatsApp Image 2023-10-10 at 12 22 16_4cc624ac](https://github.com/max-programming/hacktoberfest-projects/assets/51731966/17c7c987-a3c8-4f93-89d5-d1d8bd185cc9)

**Comment by nabarvn** [comment]
I'd like to work on it, @max-programming. ✋

**Comment by max-programming** [comment]
Best of luck!
