### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by olaoluwaayanbola** [max-programming/hacktoberfest-projects#203]
Problem: The sign-up button on the landing page of https://finder.usmans.me/ is not clearly visible due to the black background, making it difficult for users to find and access it easily.

Expected Behavior: The sign-up button should have sufficient contrast and visibility against the black background so that users can easily locate and click on it.

Steps to Reproduce
Visit the landing page at https://finder.usmans.me/.
Observe the homepage with the black background.
Attempt to find and click on the sign-up button.

**Comment by olaoluwaayanbola** [comment]
Can I be assigned this issue

**Comment by max-programming** [comment]
@olaoluwaayanbola How does it look on your end? Isn't It visible this way?
![image](https://github.com/max-programming/hacktoberfest-projects/assets/51731966/a04af81b-e357-4f91-a4cc-b122cdaf045f)

**Comment by max-programming** [comment]
Still I'd love to see the improvements you make ✌️

**Comment by olaoluwaayanbola** [comment]
It is now visible @max-programming
