### ISSUE TITLE
404 error, no language repo showing up.

### ISSUE THREAD

**Issue by Harshal-Gahlot** [max-programming/hacktoberfest-projects#211]
When I am on "https://finder.usmans.me" and click on any language button it shows error
(for ex: "https://finder.usmans.me/repos/rust", "https://finder.usmans.me/repos/python" ...)
![image](https://github.com/user-attachments/assets/c5dc4de9-04aa-4b34-818f-04f0aa15adf3)

"https://finder.usmans.me/contributors" is also throwing client side error.

**Comment by max-programming** [comment]
Interesting. Let me check and fix those asap

**Comment by max-programming** [comment]
Fixed!
