### ISSUE TITLE
C++ Language search not working

### ISSUE THREAD

**Issue by rs0125** [max-programming/hacktoberfest-projects#218]
![image](https://github.com/user-attachments/assets/63b1541b-6f80-4a98-8dea-fe68670a7695)

When the filter is applied as C++ the UI says C, and the repos then displayed are not using C++. Seems to be a fault in the filter.

**Comment by max-programming** [comment]
Thanks for pointing it out. Turns out this happened because `language` already came encoded but it was wrapped in `encodeURIComponent()`

![image](https://github.com/user-attachments/assets/46d79c02-4b88-4eff-86bf-b448f8e4d462)
