### ISSUE TITLE
Elixir Language Filtering or Searching Results in a Server-Side Exception

### ISSUE THREAD

**Issue by bentduso** [max-programming/hacktoberfest-projects#221]
When attempting to filter projects by selecting Elixir as a language using the provided buttons or explicitly searching for "Elixir" in the search bar, a server-side exception occurs. This issue may be related to #218, although I'm not sure. I've attached an screenshot showing the error message for reference:
![Screenshot 2024-10-02 at 14 08 22](https://github.com/user-attachments/assets/e111dcaa-c095-4203-97a0-c9e74dba87b9)

**Comment by max-programming** [comment]
In the latest commitI tried to fix this issue, let me know if it happens again

**Comment by bentduso** [comment]
I'm still experiencing the same issue.

**Comment by max-programming** [comment]
@bentduso How about now?

**Comment by bentduso** [comment]
It works now!
