### ISSUE TITLE
Star-range reset when selecting a new language

### ISSUE THREAD

**Issue by amandee27** [max-programming/hacktoberfest-projects#223]
Let’s say we selected a language and entered a star range to filter repos. Now if we want to find the projects between the same star range but with a different language, we have to select the language and re-enter the same star range. Because when we choose a new language, the star range reset to the initial state. I think it would be a better user experience if we could select another language without resetting the star range. The same issue happens with the sorting field as well.
<br/>
<img width="500" alt="179 REPOSITORIES" src="https://github.com/user-attachments/assets/7a93c8e2-a09f-45e4-86d7-c425dcb9d696">
Image 1: Search results for the javascript projects between 500-1000 stars
<br/>
<img width="500" alt="179 REPOSITORIES" src="https://github.com/user-attachments/assets/7087e3df-281f-4150-ba85-8caff2096cf1">
Image 2: Trying to find the python projects in the same star range(500-1000) by selecting the language
<br/>
<img width="500" alt="7708 REPOSITORIES" src="https://github.com/user-attachments/assets/72aeb854-8a31-4317-8d6a-065cfd0b0b9b">
Image 3: The star range field got reset after selecting the language as python

**Comment by amandee27** [comment]
Happy to contribute and implement this if you think this is a good feature to have @max-programming

**Comment by max-programming** [comment]
This is definitely a very good improvement!

Thanks for the issue and yes open a pr when ready ✌️

**Comment by amandee27** [comment]
Thanks !  Will open a PR within 1-2 days.
