### ISSUE TITLE
Pagination does not reset when updating search params

### ISSUE THREAD

**Issue by amandee27** [max-programming/hacktoberfest-projects#228]
The pagination does not reset to the first page after we select a new language, star range, or sorting (e.g., Best match). Ideally, it should show the first page after the search query changes.

## Steps Reproduce
1. Select 'C' as the language
2. Set the star range from 0 to 20000 and search
3. Now go to the next page (ie: 2nd page)
4. Then update the star range from 10000 to 20000 and search

**Observation:** Page not found error
**Expected:** We should show the first page for the 'C' language with the star range from 10000 to 20000 (which only has 1 page)

**Comment by amandee27** [comment]
I'm already working on a fix for this.

**Comment by max-programming** [comment]
Thanks for pointing it out and working on it ✌️
