### ISSUE TITLE
Use Next.js Image component for contributors page

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#47]
On the [contributors page of the website](https://hacktoberfest-projects.vercel.app/contributors)  right now normal `img` tags are used. It would be better to use the [Image component from Next.js](https://nextjs.org/docs/api-reference/next/image) with a placeholder of blur.

Refer to the docs for more information.

**Comment by HussainGagan** [comment]
Can I work on this issue.
