### ISSUE TITLE
Add language selection list

### ISSUE THREAD

**Issue by Rahul-Kumar-prog** [max-programming/hacktoberfest-projects#64]
When we chose a language to see hacktoberfest projects  repository on that page we don't have any language selection list to directly switch to different language project repos...
![Screenshot 2022-10-05 at 1 12 36 AM](https://user-images.githubusercontent.com/68837569/193911825-19f1f80e-b021-40fa-9c2b-490376195c22.png)

**Comment by Rahul-Kumar-prog** [comment]
Hey @max-programming please look into it. if its a valid issue then let me know.
i would love to work on it
please Assign me

**Comment by max-programming** [comment]
That's a cool idea!

**Comment by Rahul-Kumar-prog** [comment]
#68

**Comment by Rahul-Kumar-prog** [comment]
#68

**Comment by Rahul-Kumar-prog** [comment]
#68

**Comment by Go3452** [comment]
please assign me this

**Comment by Go3452** [comment]
#64

**Comment by max-programming** [comment]
> please assign me this 

But @Rahul-Kumar-prog is doing it already
