### ISSUE TITLE
Pagination when no repos available

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#71]
Pagination still shows up when there are no more repos to show. 

For example on [this page](https://dub.sh/mkNA0TK):
![image](https://user-images.githubusercontent.com/51731966/195165718-dd1137d5-d628-49b7-bf0e-9feb83b56c9a.png)

**Comment by vinmaster** [comment]
Hi, I've made a PR for this issue, please take a look: https://github.com/max-programming/hacktoberfest-projects/pull/72
