### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#74]
Right now the 404 page looks like this.

![microsoft_edge_screenshot_Oct 12, 2022 11_47_53 AM GMT+05_30.png.jpg](https://user-images.githubusercontent.com/51731966/195265265-86daa81d-2449-4627-b9a5-e7c3946152bb.jpg)

Resource: [Custom 404 page in NextJS](https://nextjs.org/docs/advanced-features/custom-error-page)

**Comment by syprogrammer** [comment]
can you assign me

**Comment by Chandak-Keshav** [comment]
Kindly assign me this @max-programming

**Comment by max-programming** [comment]
I think I will have to choose which one looks better from many submissions 🥲

**Comment by syprogrammer** [comment]
@max-programming choose design before i start to work 
here  i have created 4 designs check : https://bit.ly/3CxzVAv

**Comment by max-programming** [comment]
@syprogrammer Any updates on your 404 page?

**Comment by syprogrammer** [comment]
Today will be completed
