### ISSUE TITLE
Add Icons for language buttons

### ISSUE THREAD

**Issue by max-programming** [max-programming/hacktoberfest-projects#79]
Right now, there are no icons for the buttons. It would be better if **monotone** icons are used before the name of the language.

Please consider using [simpleicons.org](https://simpleicons.org)

![hacktoberfest-projects vercel app_(Pixel 5)](https://user-images.githubusercontent.com/51731966/195886645-02b9f821-8ba4-4e2b-83d2-efa9d3c09d4a.png)

**Comment by Anuran12** [comment]
@max-programming  Hi.... I would like to work on this

**Comment by Anuran12** [comment]
@max-programming  HI I would like to work on this

**Comment by max-programming** [comment]
Sure @Anuran12 go ahead

**Comment by Adnanarodiya** [comment]
hi bro I would like to complete this issue

**Comment by Alone-Y154** [comment]
@max-programming I would like to work on this Issue

**Comment by max-programming** [comment]
Sure @Alone-Y154

**Comment by Alone-Y154** [comment]
I've started working on it, Will raise a PR once I've finished it

**Comment by Alone-Y154** [comment]
Hi @max-programming , I have raised the PR🙂

**Comment by inbuilt-aura** [comment]
is this issue open?

**Comment by AkshatJangid787** [comment]
Can You Please Assign Me This Project I Would be So Much Glad To Contribute In This project

**Comment by Alone-Y154** [comment]
Actually PR have be raised for this Issue awaiting for approval🙂, Thank You

**Comment by Keshavraj52** [comment]
I hope this message finds you well! I'm eager to contribute more to our project. plz assign this issue to me i will handle it

**Comment by max-programming** [comment]
Actually @Alone-Y154 has already taken this up
