### ISSUE TITLE
Add Clojure at the other languages list 

### ISSUE THREAD

**Issue by marcopollivier** [max-programming/hacktoberfest-projects#89]
Hi, I'd like to propose adding the Clojure lang as a new language

I'm creating two new libs that I'd like to make available to the community to participate. 

I think this project can help projects in Clojure to participate to the Hacktoberfest

**Comment by marcopollivier** [comment]
![Uploading image.png…]()

🙈

**Comment by marcopollivier** [comment]
I did it local to test hehe 🙈 

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/697445/197061937-b737fff1-6fd2-440e-9c9e-cf42a3b87474.png">

**Comment by max-programming** [comment]
Thanks @marcopollivier for the suggestion. I will add it

Unfortunately I can't accept PRs for adding languages because last year this repo got in the spam category

**Comment by max-programming** [comment]
@all-contributors please add @marcopollivier for ideas
